package com.meonghae.communityservice.mock;

import com.meonghae.communityservice.application.board.port.CommentRepository;
import com.meonghae.communityservice.domain.board.BoardComment;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Slice;

import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

public class FakeCommentRepo implements CommentRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0L);
    private final List<BoardComment> data = new ArrayList<>();

    @Override
    public Optional<BoardComment> findById(Long commentId) {
       return data.stream().filter(comment -> comment.getId().equals(commentId)).findAny();
    }

    @Override
    public Slice<BoardComment> findByBoard_IdAndParentIsNull(Pageable pageable, Long boardId) {
        return null;
    }

    @Override
    public Slice<BoardComment> findByParent_Id(Pageable pageable, Long parentId) {
        return null;
    }

    @Override
    public Map<Long, Long> findCommentCountByBoardIds(List<Long> boardIds) {
        return null;
    }

    @Override
    public BoardComment save(BoardComment comment) {
        if (comment.getId() == null || comment.getId() == 0) {
            BoardComment saveComment = BoardComment.builder()
                    .id(autoGeneratedId.incrementAndGet())
                    .email(comment.getEmail())
                    .parent(comment.getParent() == null ? null : comment.getParent())
                    .updated(comment.getUpdated())
                    .replies(comment.getReplies())
                    .createdDate(comment.getCreatedDate())
                    .modifiedDate(comment.getModifiedDate())
                    .comment(comment.getComment())
                    .board(comment.getBoard())
                    .build();

            data.add(saveComment);
            return saveComment;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), comment.getId()));
            data.add(comment);
            return comment;
        }
    }

    @Override
    public BoardComment saveChild(BoardComment parent, BoardComment child) {
        BoardComment saveComment = BoardComment.builder()
                .id(autoGeneratedId.incrementAndGet())
                .email(child.getEmail())
                .parent(parent)
                .updated(child.getUpdated())
                .replies(child.getReplies())
                .createdDate(child.getCreatedDate())
                .modifiedDate(child.getModifiedDate())
                .comment(child.getComment())
                .board(child.getBoard())
                .build();

        data.add(saveComment);

        parent.addReply(saveComment);
        data.removeIf(item -> Objects.equals(item.getId(), parent.getId()));
        data.add(parent);

        return saveComment;
    }

    @Override
    public void delete(Long commentId) {

    }

    @Override
    public int countByBoardId(Long boardId) {
        return 0;
    }
}
