package com.meonghae.communityservice.mock;

import com.meonghae.communityservice.application.port.UserServicePort;
import com.meonghae.communityservice.dto.fcm.FcmDto;

import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;

public class FakeUserService implements UserServicePort {
    private final AtomicLong autoGeneratedId = new AtomicLong(0L);

    @Override
    public String getUserEmail(String token) {
        if (!Objects.equals(token, "unknown token")) {
            return token + "@test.com";
        } else {
            return null;
        }
    }

    @Override
    public String getNickname(String email) {
        return "tester";
    }

    @Override
    public FcmDto getFCMToken(String email) {
        return null;
    }
}
